### ISSUE TITLE
(rough) start to landing page

### ISSUE THREAD

**Issue by jgravois** [jgravois/freehub-css#1]
you can find a live version of the primary content of the landing page that collapses into a single column on screens less than 800px here:

https://johngravois.com/freehub-css/index.html

<img width="728" alt="Screen Shot 2019-12-03 at 8 32 21 PM" src="https://user-images.githubusercontent.com/3011734/70112993-3d2d0280-160c-11ea-9973-720d7e88b2ff.png">

so far its header-less and footer-less, but its a start.

cc/ @asalant

**Comment by asalant** [comment]
Awesome.

I've been working on getting Freehub running on Docker with a setup that is easy for development and let's me easily play with database upgrades (as that is what I am first working on). I updated the [developer guide](https://github.com/asalant/freehub/wiki/Freehub-Developer-Guide) with info on how to get set up. If you have a chance to check it out, please do as I would love feedback.

**Comment by jgravois** [comment]
> If you have a chance to check it out, please do as I would love feedback.

absolutely. it felt a bit simpler to write the .css against static .html, but I didn't have too much trouble with the docker setup before, so when it's time to plug in the new styles in the real app, I'll holler if I need any help.

**Comment by jgravois** [comment]
alright @asalant, I've chipped away at the new .css over the last couple nights and I'm finally satisfied with the new mock [responsive landing page](https://johngravois.com/freehub-css/index.html).

I'm no designer, my goals were just to
1. make it look as similar as possible
2. minimize the amount of changes necessary in each template in rubyland.

is this what you had in mind?
are you open to me giving the original design an actual facelift to take her into 2020 in style? if so, I could probably recruit a little help.

as far as the nitty gritty details go, I'm not using a framework like bootstrap or anything, just plain old [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout). browser support for it is pretty widespread at this point.

https://caniuse.com/#search=css-grid

**Comment by asalant** [comment]
Hey John, this is great.

I did some investigation of my own on Friday and was starting to formulate a plan that is pretty similar to yours with the same goals. It may be even simpler. It's a bit hard for me to tell the scope of the changes required to follow your approach with CSS grid. Would it be possible to create a branch to Freehub that shows the changes to the CSS files to get to where you are now?

I'll push a work-in-progress PR for what I was doing on Friday to show you what I was thinking. We can see how close we are and take it from there.

Regarding visual redesign, I'm definitely into bringing things to a more current look-and-feel but am inclined to address that separately from responsive work. I think we can get to a place that is good for tablets and phones with fairly minor changes and therefore ship it to users soon.

**Comment by jgravois** [comment]
> It's a bit hard for me to tell the scope of the changes required to follow your approach with CSS grid [....] Would it be possible to create a branch to Freehub that shows the changes to the CSS files to get to where you are now?

absolutely.

**Comment by asalant** [comment]
Great. Looking a little closer at what you are doing, I think we should go with your approach. If you just branch off master and apply the changes to the existing application.css (even just the core css-grid stuff), that would be super helpful.

The developer guide has updated info on how to run Freehub with docker that I hope works well for you.

**Comment by jgravois** [comment]
moving to https://github.com/asalant/freehub/pull/43
